<a href="https://colab.research.google.com/github/HeroHalder/AI-ML-Zero-to-Hero/blob/main/02%20Python%20Libraries/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hero")

Hero

In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([1,2,3,4,5,6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.values

array([1, 2, 3, 4, 5, 6])

In [ ]:
s.name

In [ ]:
s.name="Numbers"

In [ ]:
s

0    1
1    2
2    3
3    4
4    5
5    6
Name: Numbers, dtype: int64

In [ ]:
#Indexing
s[0]

np.int64(1)

In [ ]:
s[0:2]

0    1
1    2
Name: Numbers, dtype: int64

In [ ]:
s[2:4]

2    3
3    4
Name: Numbers, dtype: int64

In [ ]:
#iloc -> location based indexing
s.iloc[3]

np.int64(4)

In [ ]:
s.iloc[[1,3,4]]

1    2
3    4
4    5
Name: Numbers, dtype: int64

In [ ]:
index=["apple","banana","mango","orange","grapes","strowberry"]
index

['apple', 'banana', 'mango', 'orange', 'grapes', 'strowberry']

In [ ]:
s.index=index
s

apple         1
banana        2
mango         3
orange        4
grapes        5
strowberry    6
Name: Numbers, dtype: int64

In [ ]:
s["orange"]

np.int64(4)

In [ ]:
s['orange']

np.int64(4)

In [ ]:
s.iloc[5]

np.int64(6)

In [ ]:
#loc -> label based indexing
s.loc["grapes"]

np.int64(5)

In [ ]:
s["banana":"orange"]

banana    2
mango     3
orange    4
Name: Numbers, dtype: int64

In [ ]:
s.loc[["grapes","orange"]]

grapes    5
orange    4
Name: Numbers, dtype: int64

In [ ]:
fruit_protein={
    "Guava":2.6,
    "🥑":2.0,
    "Avocado":2.0,
    "orange":0.9,
    "🍌":1.1,
    "🍏":0.3,
    "🥝":1.1,
    "kiwi":1.1,
    "mango":0.8,
    "🍒":1.0,
    "cherries":1.0
}
fruit_protein

{'Guava': 2.6,
 '🥑': 2.0,
 'Avocado': 2.0,
 'orange': 0.9,
 '🍌': 1.1,
 '🍏': 0.3,
 '🥝': 1.1,
 'kiwi': 1.1,
 'mango': 0.8,
 '🍒': 1.0,
 'cherries': 1.0}

In [ ]:
s2=pd.Series(fruit_protein,name="Protein")
s2

Guava       2.6
🥑           2.0
Avocado     2.0
orange      0.9
🍌           1.1
🍏           0.3
🥝           1.1
kiwi        1.1
mango       0.8
🍒           1.0
cherries    1.0
Name: Protein, dtype: float64

In [ ]:
#Conditional Selection:
s2>1

Guava        True
🥑            True
Avocado      True
orange      False
🍌            True
🍏           False
🥝            True
kiwi         True
mango       False
🍒           False
cherries    False
Name: Protein, dtype: bool

In [ ]:
s2[s2>1]

Guava      2.6
🥑          2.0
Avocado    2.0
🍌          1.1
🥝          1.1
kiwi       1.1
Name: Protein, dtype: float64

In [ ]:
#Logical Operators
(s2>0.5) & (s2<2) #AND

Guava       False
🥑           False
Avocado     False
orange       True
🍌            True
🍏           False
🥝            True
kiwi         True
mango        True
🍒            True
cherries     True
Name: Protein, dtype: bool

In [ ]:
[(s2>0.5) & (s2<2)]

[Guava       False
 🥑           False
 Avocado     False
 orange       True
 🍌            True
 🍏           False
 🥝            True
 kiwi         True
 mango        True
 🍒            True
 cherries     True
 Name: Protein, dtype: bool]

In [ ]:
s2[(s2>0.5) & (s2<2)]

orange      0.9
🍌           1.1
🥝           1.1
kiwi        1.1
mango       0.8
🍒           1.0
cherries    1.0
Name: Protein, dtype: float64

In [ ]:
(s2>0.5) | (s2<2) #OR

Guava       True
🥑           True
Avocado     True
orange      True
🍌           True
🍏           True
🥝           True
kiwi        True
mango       True
🍒           True
cherries    True
Name: Protein, dtype: bool

In [ ]:
#NOT
s2[~(s2>1)]

orange      0.9
🍏           0.3
mango       1.0
🍒           1.0
cherries    1.0
Name: Protein, dtype: float64

In [ ]:
#Modyfying Series
s2["mango"]=1.0

**DataFrame**

In [ ]:
#DataFrame
data={
    "Name":["Alice","Bob","Charlie"],
    "Age":[25,30,35],
    "Department":["CSE","ADS","SWE"],
    "Salary":[50000,60000,70000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie'],
 'Age': [25, 30, 35],
 'Department': ['CSE', 'ADS', 'SWE'],
 'Salary': [50000, 60000, 70000]}

In [ ]:
df=pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   25        CSE   50000
1      Bob   30        ADS   60000
2  Charlie   35        SWE   70000

In [ ]:
df.head(2)

    Name  Age Department  Salary
0  Alice   25        CSE   50000
1    Bob   30        ADS   60000

In [ ]:
df.tail(1)

      Name  Age Department  Salary
2  Charlie   35        SWE   70000

In [ ]:
#loc and iloc
df.iloc[1:3]

      Name  Age Department  Salary
1      Bob   30        ADS   60000
2  Charlie   35        SWE   70000

In [ ]:
df.iloc[1:3, :2]

      Name  Age
1      Bob   30
2  Charlie   35

In [ ]:
df.loc[1:2,["Age","Department"]] #for loc starting and ending will included

   Age Department
1   30        ADS
2   35        SWE

In [ ]:
df["Age"]

0    25
1    30
2    35
Name: Age, dtype: int64

In [ ]:
df[["Age","Department"]]

   Age Department
0   25        CSE
1   30        ADS
2   35        SWE

In [ ]:
df.drop("Age",axis=1)

      Name Department  Salary
0    Alice        CSE   50000
1      Bob        ADS   60000
2  Charlie        SWE   70000

In [ ]:
df

      Name  Age Department  Salary
0    Alice   25        CSE   50000
1      Bob   30        ADS   60000
2  Charlie   35        SWE   70000

In [ ]:
df.drop("Age",axis=1) #,inplae=True

In [ ]:
df.drop(2,axis=0)

    Name  Age Department  Salary
0  Alice   25        CSE   50000
1    Bob   30        ADS   60000

In [ ]:
df

      Name  Age Department  Salary
0    Alice   25        CSE   50000
1      Bob   30        ADS   60000
2  Charlie   35        SWE   70000

In [ ]:
df.shape

(3, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      object
 1   Age         3 non-null      int64
 2   Department  3 non-null      object
 3   Salary      3 non-null      int64
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

        Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0

In [ ]:
#Broadcasting
df["Salary"]= df["Salary"]+5000

In [ ]:
#Renaming Columns
df.rename(columns={"Department":"Dept"},inplace=True)
df

      Name  Age Dept  Salary
0    Alice   25  CSE   60000
1      Bob   30  ADS   70000
2  Charlie   35  SWE   80000

In [ ]:
df["Dept"].unique()

array(['CSE', 'ADS', 'SWE'], dtype=object)

In [ ]:
df["Dept"].value_counts()

Dept
CSE    1
ADS    1
SWE    1
Name: count, dtype: int64

In [ ]:
df["Promoted Salary"]=df["Salary"]*10
df

      Name  Age Dept  Salary  Promoted Salary
0    Alice   25  CSE   60000           600000
1      Bob   30  ADS   70000           700000
2  Charlie   35  SWE   80000           800000

In [ ]:
import numpy as np
df.loc[1:1,["Age"]]=np.nan
df

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000           600000
1      Bob   NaN  ADS   70000           700000
2  Charlie  35.0  SWE   80000           800000

In [ ]:
#Data cleaning
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             0
Promoted Salary    0
dtype: int64

In [ ]:
df.dropna()

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000           600000
2  Charlie  35.0  SWE   80000           800000

In [ ]:
df.dropna(how="any")#any null of any row it del the row

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000           600000
2  Charlie  35.0  SWE   80000           800000

In [ ]:
df.dropna(how="all")#all value of a row is null then dlt

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000           600000
1      Bob   NaN  ADS   70000           700000
2  Charlie  35.0  SWE   80000           800000

In [ ]:
df.fillna(0)

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000           600000
1      Bob   0.0  ADS   70000           700000
2  Charlie  35.0  SWE   80000           800000

In [ ]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
Name: Age, dtype: float64

In [ ]:
df

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000           600000
1      Bob   NaN  ADS   70000           700000
2  Charlie  35.0  SWE   80000           800000

In [ ]:
df["Age"].fillna(df["Age"].median())

0    25.0
1    30.0
2    35.0
Name: Age, dtype: float64

In [ ]:
df

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000           600000
1      Bob   NaN  ADS   70000           700000
2  Charlie  35.0  SWE   80000           800000

In [ ]:
#Forward Fill And Backword Fill
df["Age"].fillna(method="ffill")

/tmp/ipykernel_1138/87066624.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="ffill")

0    25.0
1    25.0
2    35.0
Name: Age, dtype: float64

In [ ]:
df["Age"].fillna(method="bfill")

/tmp/ipykernel_1138/3345892411.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="bfill")

0    25.0
1    35.0
2    35.0
Name: Age, dtype: float64

In [ ]:
df["Name"].replace("Bob","Rose") #temp

0      Alice
1       Rose
2    Charlie
Name: Name, dtype: object

In [ ]:
df["Name"]=df["Name"].replace("Bob","Rose")#cng in original DS
df #Permanant Changed

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000           600000
1     Rose   NaN  ADS   70000           700000
2  Charlie  35.0  SWE   80000           800000

In [ ]:
#Duplicates
df_dup=df[df.duplicated()]
df_dup

Empty DataFrame
Columns: [Name, Age, Dept, Salary, Promoted Salary]
Index: []

In [ ]:
#Duplicates
df_dup=df[df.duplicated(keep="first")]#if last then first will be marked as dup
df_dup

In [ ]:
df=df.drop_duplicates()
df

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000           600000
1     Rose   NaN  ADS   70000           700000
2  Charlie  35.0  SWE   80000           800000

In [ ]:
#invalid values
#Lambda
df["Promoted Salary"]=df["Promoted Salary"].apply(lambda x: x/10 if x>600000 else x)
df

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000         600000.0
1     Rose   NaN  ADS   70000          70000.0
2  Charlie  35.0  SWE   80000          80000.0

In [ ]:
name="Alice_Smith" #Demo
df[["first_name","last_name"]]=df["name"].str.split("_")

KeyError: 'name'

In [ ]:
#apply and lambda
def multiplying_age(x):
  return x*2

df["Age"]=df["Age"].apply(multiplying_age)

In [ ]:
df

      Name    Age Dept  Salary  Promoted Salary
0    Alice  200.0  CSE   60000         600000.0
1     Rose    NaN  ADS   70000          70000.0
2  Charlie  280.0  SWE   80000          80000.0

In [ ]:
df["Age"]=df["Age"].apply(lambda x: x/2)
df

      Name   Age Dept  Salary  Promoted Salary
0    Alice  25.0  CSE   60000         600000.0
1     Rose   NaN  ADS   70000          70000.0
2  Charlie  35.0  SWE   80000          80000.0

In [ ]:
#Joins and Merges
dept_info={
    "Dept":["CSE","ADS","SWE"],
    "Location":["US","Swidz","IN"]
}
df2=pd.DataFrame(dept_info)
df2

  Dept Location
0  CSE       US
1  ADS    Swidz
2  SWE       IN

In [ ]:
pd.concat([df,df2])

      Name   Age Dept   Salary  Promoted Salary Location
0    Alice  25.0  CSE  60000.0         600000.0      NaN
1     Rose   NaN  ADS  70000.0          70000.0      NaN
2  Charlie  35.0  SWE  80000.0          80000.0      NaN
0      NaN   NaN  CSE      NaN              NaN       US
1      NaN   NaN  ADS      NaN              NaN    Swidz
2      NaN   NaN  SWE      NaN              NaN       IN

In [ ]:
pd.concat([df,df2],axis=1)

      Name   Age Dept  Salary  Promoted Salary Dept Location
0    Alice  25.0  CSE   60000         600000.0  CSE       US
1     Rose   NaN  ADS   70000          70000.0  ADS    Swidz
2  Charlie  35.0  SWE   80000          80000.0  SWE       IN

In [ ]:
pd.merge(df,df2,on="Dept")

      Name   Age Dept  Salary  Promoted Salary Location
0    Alice  25.0  CSE   60000         600000.0       US
1     Rose   NaN  ADS   70000          70000.0    Swidz
2  Charlie  35.0  SWE   80000          80000.0       IN

In [ ]:
data=pd.read_csv("CSE 315 - 223D2 - Presentation Details - Sheet1.csv.csv")

In [ ]:
data.head(50)

,SL,ID,Name,Paper Link
0,1.0,222902078.0,Anisur Rahaman Maruf,Object Detection in Adverse Weather for Autono...
1,NaN,222902083.0,Sakibul Hasan,NaN
2,NaN,222902089.0,Mahabub Hasan Tamim,NaN
3,NaN,NaN,NaN,NaN
4,2.0,223002011.0,Kazi Saqlain Mihad,BanglaLem: A Transformer-based Bangla Lemmatiz...
5,NaN,223002083.0,Abdullah Sardar,NaN
6,NaN,223002120.0,Taher Mahmud Monmoy,NaN
7,NaN,NaN,NaN,NaN
8,3.0,222002014.0,Saifulla Tanim,https://arxiv.org/abs/1604.07316
9,NaN,222002104.0,Mim Akter,NaN
10,NaN,221902124.0,Md.Emam Hossain,NaN
11,NaN,NaN,NaN,NaN
12,4.0,223902041.0,Tamimur Rahman,https://www.nature.com/articles/s41598-025-980...
13,NaN,223902089.0,Maharun Akther Akhi,NaN
14,NaN,223902010.0,Hriday Mia,NaN
15,NaN,NaN,NaN,NaN
16,5.0,223002058.0,Miftahul Haque,Lightweight Deep Learning Architecture for Mul...
17,NaN,223902040.0,Niloy Chakkraborty,NaN
18,NaN,223002100.0,Saleh Uddin,NaN
19,NaN,NaN,NaN,NaN
20,6.0,223002047.0,Nadia Islam Rupa,Explainable Machine-Learning Model for Predict...
21,NaN,223002063.0,Kawser Miah,NaN
22,NaN,223002111.0,Afsa Akter Shawla,NaN
23,NaN,NaN,NaN,NaN
24,7.0,242002122.0,Hero Halder,https://openaccess.thecvf.com/content_cvpr_201...
25,NaN,223902001.0,Tasmia Noor Tama,NaN
26,NaN,223902055.0,Kaniz Fatema Liza,NaN
27,NaN,213902098.0,Maria Akhter,NaN
28,NaN,NaN,NaN,NaN
29,8.0,223002024.0,Golam Sarwar Him,https://www.ijert.org/research/a-literature-su...
30,NaN,223002033.0,Md. Abu Touhid,NaN
31,NaN,223002070.0,Toukir Khondokar,NaN
32,NaN,223002131.0,Md. Maswdur Rahman,NaN
33,NaN,NaN,NaN,NaN
34,9.0,223002080.0,Abdullah Al Fuad,https://arxiv.org/pdf/2403.02164v2
35,NaN,223002147.0,Ariful Islam,NaN
36,NaN,223002158.0,Sanjid Alom Araf,NaN
37,NaN,NaN,NaN,NaN
38,10.0,223002076.0,Sajib Saha,Ensemble-based Convolutional Neural Networks f...
39,NaN,223002114.0,M.A Rakib Sarkar,NaN
40,NaN,223902023.0,Raisa Jahan Rini,NaN
41,NaN,NaN,NaN,NaN
42,11.0,223002124.0,Most: Anni Akther,https://www.researchgate.net/publication/37789...
43,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN
45,12.0,221902305.0,Md Rezanur Bin Shamim,https://www.researchgate.net/publication/39454...
46,NaN,221002295.0,Pronoy Banik,NaN
47,NaN,221002481.0,Md. Yousuf Ibna Alam Joy,NaN
48,NaN,NaN,NaN,NaN
49,13.0,222902029.0,Mehedi Sarkar,https://arxiv.org/pdf/1709.01507

In [ ]:
data.shape

(62, 4)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SL          16 non-null     float64
 1   ID          43 non-null     float64
 2   Name        44 non-null     object
 3   Paper Link  16 non-null     object
dtypes: float64(2), object(2)
memory usage: 2.1+ KB

In [ ]:
data.describe

<bound method NDFrame.describe of       SL           ID                   Name  \
0    1.0  222902078.0   Anisur Rahaman Maruf
1    NaN  222902083.0          Sakibul Hasan
2    NaN  222902089.0    Mahabub Hasan Tamim
3    NaN          NaN                    NaN
4    2.0  223002011.0     Kazi Saqlain Mihad
..   ...          ...                    ...
57  15.0          NaN                    NaN
58   NaN  221002268.0  Sheikh Adnan Mostofa
59   NaN          NaN                    NaN
60  16.0          NaN                    NaN
61   NaN          NaN      Md. Hasibul Islam

                                           Paper Link
0   Object Detection in Adverse Weather for Autono...
1                                                 NaN
2                                                 NaN
3                                                 NaN
4   BanglaLem: A Transformer-based Bangla Lemmatiz...
..                                                ...
57  Enhancing_Robustness_of_Machine_Learning_Algor...
58                                                NaN
59                                                NaN
60               https://arxiv.org/abs/2211.06318?utm
61                                                NaN

[62 rows x 4 columns]>